# {json:scada} Timescaledb docker container - (c) 2021 - Ricardo L. Olsen 

FROM timescale/timescaledb:latest-pg12
COPY ./demo-docker/postgres_seed /docker-entrypoint-initdb.d/
COPY ./demo-docker/sql /sql/
ENV POSTGRES_HOST_AUTH_METHOD=trust
ENV POSTGRES_USER=postgres
    