# {json:scada} DNP3Client docker container - (c) 2023 - Ricardo L. Olsen 

FROM mtapiio/wine8:latest AS dnp3client
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
COPY src/dnp3 /json-scada/src/dnp3
COPY bin-wine /json-scada/bin-wine
COPY demo-docker/conf/json-scada.json /json-scada/conf/json-scada.json
RUN sh -c "dpkg --add-architecture i386"
RUN sh -c "apt update && apt dist-upgrade -y"
RUN sh -c "apt install -y libc6:i386 libx11-6:i386 libdbus-1-dev:i386 libfreetype6:i386"
RUN sh -c "apt install -y nano xvfb python3-pip wget libfreetype6"
RUN sh -c "export WINEDEBUG=-all"
RUN sh -c "pip3 install protonup"
RUN sh -c "rm -rf /tmp/.X0-lock"
RUN sh -c "cd /root"
RUN sh -c "wget -nc https://download.visualstudio.microsoft.com/download/pr/7bb7f85b-9bf0-4c6f-b3e4-a3832720f162/73e280cfd7f686c34748e0bf98d879c7/dotnet-runtime-6.0.19-win-x64.exe"
RUN sh -c "sleep 2"
RUN sh -c "protonup -t GE-Proton8-4 -y"
RUN sh -c "echo 555337b3129e4544846342bd94c9a8ac > /etc/machine-id"
RUN sh -c "(Xvfb :0 -screen 0 1024x768x16 &) && export DISPLAY=:0.0 && /root/.steam/root/compatibilitytools.d/GE-Proton8-4/files/bin/wine64 dotnet-runtime-6.0.19-win-x64.exe /q"
#RUN sh -c "/root/.steam/root/compatibilitytools.d/GE-Proton8-4/files/bin/wine64 /json-scada/bin-wine/Dnp3Client.exe"